-- Exercice 3.1 – Inscrivez-vous comme étudiant dans la base de données DBSlide sans
-- spécifier les noms de colonnes dans lesquelles on insère les données

    -- Comme il manque l'auto génération d'id dans la table student je vais le créer
    ALTER TABLE student
        ALTER COLUMN student_id
        ADD GENERATED BY DEFAULT AS IDENTITY;

    -- Et comme la table student contient déjà des valeurs on va set le default
    SELECT setval(
        pg_get_serial_sequence('student', 'student_id'),
        (SELECT MAX(student_id) FROM student)
    );

    INSERT INTO student VALUES 
        (DEFAULT, 'Anthony', 'Mets', '1986-08-19 21:45:00', 'amets', 1320, 18, 'EG2210');

-- Exercice 3.2 – Inscrivez votre voisin comme étudiant dans la base de données DBSlide.
-- Votre voisin n’aura ni nom de famille, ni login, ni résultat annuel (valeurs NULL)

    INSERT INTO student VALUES
        (DEFAULT,'Toto', NULL,'2026-08-13 14:37:00', NULL, 1110, NULL, '0');

-- Exercice 3.3 – Créer une table « section_archives » qui contiendra une copie des
-- données contenues dans la table section

    SELECT * INTO section_archive
    FROM section;

-- Exercice 3.4 – Insérer un nouvel étudiant dans la base de données. Cet étudiant sera
-- inscrit dans la même section que Keanu Reeves, assistera au cours donné par le professeur
-- Zidda (les lettres ‘EG’ suivies des 4 derniers caractères du cours en question) mais n’aura
-- pas de login. Les valeurs de l’id de section et du cours devront être récupérées là où elles se
-- trouvent dans la base de données, sans les renseigner directement

    -- Aucun course_id n'existe avec les bonnes données donc je vais modifier la table courses et la valeur pour Keanu
    ALTER TABLE student
        ALTER COLUMN course_id TYPE VARCHAR(8);

    UPDATE student
    SET course_id = 'ECGE2184' WHERE lower(first_name) = 'keanu' AND lower(last_name) = 'reeves';

    INSERT INTO student (first_name, last_name, section_id, course_id, login) VALUES
        (
            'Riri',
            'Duck',
            (SELECT section_id FROM student WHERE lower(first_name) = 'keanu' AND lower(last_name) = 'reeves'),
            (SELECT c.course_id FROM course c LEFT JOIN professor p ON p.professor_id = c.professor_id WHERE lower(p.professor_name) = 'zidda'),
            NULL
        );

-- Exercice 3.5 – Insérer une nouvelle section dans la table section qui portera l’ID de
-- section 1530, qui aura l’intitulé « Administration des SI » et qui aura le même délégué que
-- la section dont l’ID et 1010 (vous ne connaissez pas la valeur de l’ID de ce délégué)

    INSERT INTO section (section_id, section_name, delegate_id) VALUES
        (
            1530,
            'Administration des SI',
            (SELECT delegate_id FROM section WHERE section_id = 1010)
        )

-- Exercice 3.6 – Mettre à jour vos propres données pour vous inscrire au cours EG2210

    UPDATE student 
    SET course_id = 'EG2210' WHERE login = 'amets';

-- Exercice 3.7 – Mettre à jour les données de votre voisin pour qu’il ait un nom. Ensuite,
-- refaire une mise à jour de la même ligne de données et attribuer à votre voisin un résultat
-- de 18/20 et un login correspondant à la concaténation de la première lettre de son prénom
-- et de la totalité de son nom, le tout en minuscules (sans connaître les valeurs réelles du
-- nom et du prénom utilisés)

    UPDATE student 
    SET last_name = 'machin' WHERE lower(first_name) = 'toto';

    UPDATE student
    SET 
        year_result = 18,
        login = lower(concat(substring(first_name,1,1),last_name))
    WHERE lower(first_name) = 'toto';

-- Exercice 3.8 – Mettre à jour les données de la table « student » pour que tous les
-- étudiants de la section 1010 aient 15/20

    UPDATE student
    SET year_result = 15 WHERE section_id = 1010;

-- Exercice 3.9 – Nommer Keanu Reeves délégué de la section 1530 (sans connaître la
-- valeur réelle de l’ID de M. Reeves)

    UPDATE section
    SET delegate_id = (
        SELECT student_id
        FROM student
        WHERE lower(first_name) = 'keanu' AND lower(last_name) = 'reeves'
        )
    WHERE section_id = 1530;

-- Exercice 3.10 – Donner à la section 1530 le même nom de section et le même délégué
-- que la section 1320 (en allant rechercher ces valeurs via la requête, pas en les renseignant
-- directement)

    UPDATE section
    SET
        section_name = (SELECT section_name FROM section WHERE section_id = 1320),
        delegate_id = (SELECT delegate_id FROM section WHERE section_id = 1320)
    WHERE section_id = 1530;

-- Exercice 3.11 – Nommer Alyssa Milano déléguée de sa section. On ne connait pas la
-- valeur réelle de la section dans laquelle Mlle Milano est inscrite

    UPDATE section
    SET delegate_id = (SELECT student_id FROM student WHERE lower(first_name) = 'Alyssa' AND lower(last_name) = 'Milano')
    WHERE section_id = (SELECT section_id FROM student WHERE lower(first_name) = 'Alyssa' AND lower(last_name) = 'Milano');

-- Exercice 3.12 – Supprimer votre voisin de la base de données

    DELETE FROM student WHERE lower(first_name) = 'toto';

-- Exercice 3.13 – Retirez-vous ainsi que Kim Basinger de la base de données. Comment se
-- fait-il que le système accepte cette manipulation alors que Mlle. Basinger est déléguée de
-- section ?

    DELETE FROM student WHERE login = 'amets' OR login = 'kbasinge';

    -- Suppression possible car aucun student n'est référencé comme FK dans la table section

-- Exercice 3.14 – Supprimer tous les étudiants qui ont moins de 8/20

    DELETE FROM student WHERE year_result < 8;

-- Exercice 3.15 – Supprimer tous les cours qui n’ont pas de professeur

    DELETE FROM course WHERE professor_id IS NULL;

-- Exercice 3.16 (bonus DDL-DML) – Sans supprimer les clés étrangères au préalable,
-- supprimer les données de toutes les tables dans l’ordre suivant : sections => professeurs =>
-- étudiants => cours => grades. Il est possible qu’il faille d’abord modifier la structure des
-- tables (ALTER TABLE) afin d’accepter des valeurs nulles à certains endroits… Une
-- modification des données des tables sous-jacentes avant la suppression de certaines
-- données sera sûrement nécessaire également

    